<?php

declare(strict_types=1);

namespace Atom\Database\Schema\Compiler;

final class PostgresSchemaCompiler extends AbstractSchemaCompiler
{
    protected function name(string $name): string
    {
        return '"' . str_replace('"', '""', $name) . '"';
    }

    protected function autoIncrement(): string
    {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    protected function stringType(int $length): string
    {
        return "VARCHAR({$length})";
    }

    protected function textType(): string
    {
        return "TEXT";
    }

    protected function integerType(): string
    {
        return "INTEGER";
    }

    protected function bigIntegerType(): string
    {
        return "BIGINT";
    }

    protected function floatType(): string
    {
        return "DOUBLE PRECISION";
    }

    protected function decimalType(int $precision, int $scale): string
    {
        return "DECIMAL({$precision}, {$scale})";
    }

    protected function booleanType(): string
    {
        return "BOOLEAN";
    }

    protected function dateType(): string
    {
        return "DATE";
    }

    protected function dateTimeType(): string
    {
        return "TIMESTAMP";
    }

    protected function timestampType(): string
    {
        return "TIMESTAMP";
    }

    protected function jsonType(): string
    {
        return "JSONB";
    }

    protected function binaryType(): string
    {
        return "BYTEA";
    }

    protected function uuidType(): string
    {
        return "UUID";
    }
}
